### ISSUE TITLE
CSS Modules localIdentName configuration

### ISSUE THREAD

**Issue by helios1138** [kitze/custom-react-scripts#97]
Is it possible to configure `localIdentName` to be something else? Specifically, to have it be different for `development` and `production` builds? Currently it puts a huge hash in both. Preferably, I would like to have something readable, like `[name]_[local]____[hash:base64:2]` in dev and the default hash (with no options or local names) in prod.

**Comment by helios1138** [comment]
any help?

**Comment by SamMcFaddenBJSS** [comment]
Hello. Thanks for all the work on this package. It would be great to be able to configure the localIdentName or make the default as helios suggests. Any chance of this please? Thanks!

**Comment by rodrigocfd** [comment]
Right now this configuration is hardcoded [right here](https://github.com/kitze/custom-react-scripts/blob/e6cdbfcf912a04247ff24a93c139d6cac2e3365c/packages/react-scripts/config/custom-react-scripts/webpack-config/style-loader.js#L23). It would be nice to have this constant configurable through **.env** file, with the code being something like this:

    localIdentName:
      process.env.REACT_APP_CSS_MODULE_IDENT_NAME ||
      '[sha512:hash:base32]-[name]-[local]',

So that it wouldn't break anything...

What about this, @kitze?
